 - Machine learning is changing things(data) into numbers and then finding patterns in those numbers.
 - In traditional programming there is Input--->SomeOperation----->Output
 - But in ML, we give the computer Input and Ideal Output and it figures on its own what operations to perform.

Why use Deep Learning?
Well, for a complex problem can you think of all the rules? (probably not)</br>
I think you can use ML for literally anything as long as you can **convert it into numbers**
and program it to find patterns. 

#### When to use ML?
- Problems with long lists of rules
- Continually changing enviroments
- Discovering insights within large collections of data
#### When not to use ML?
- When you need explainability
- Traditonal Approach is a better option
- When errors are unacceptable
- When you dont have huge data

ML vs DL
- ML works good on structured data and DL works good on Unstructured data
- ML algorithms are referred as shallow algorithms
- Ml algos -> RandomForest, NaiveBayes, NearestNeighbour, SupportVectorMachines
- DL alogs -> Neural Networks, Fully Connected NN, CNN, RNN, Transformers


#### What are Neural Networks?
Firstly we have input then we convert it into numbers before transferring to neural networks. <<**Input Layer**>> </br> 
Then feed the numbers into the NN that learns representations (patterns/features/weights) and <<**Hidden Layer**>> </br>
we get representation outputs which then are made human understable. <<**Output Layer**>>



#### Types of learning
- Supervised Learning -> All data and Labels
- Semi-Supervised Learning -> All data and some Labels
- Unsupervised Learning -> All data no labels
- Transfer Learning -> Learn Patterns from one set of data and find patterns by using it on another set of data


#### What is deep learning used for?
Recommendation, Seq2Sequence(Translation, Speech Recognition), Classification or Regression(Computer Vision, Natural Language Processing,) 

#### What is a tensor?
A tensor is representing data into some sort of numerical form


## What's Covered in here
- Introduction to tensors
- Getting informations from tensors
- Manipulating tensor
- Tensors and Numpy
- Using tf.fuction (a way to speed up your regular Python functions)
- Using GPUs with Tensorflow (TPUs)


In [2]:
import tensorflow as tf
tf.__version__

2023-08-18 00:18:55.167847: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


2023-08-18 00:18:55.868061: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


'2.13.0'

In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

2023-08-18 00:18:56.687483: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-18 00:18:56.712373: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-18 00:18:56.712823: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check Dimension which corresponds to the len(shape of tensor)
scalar.ndim

0

In [5]:
# Create Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[1,2],[2,1]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Changing dtype
f_vector = tf.constant([1,2,3],dtype=float)
f_vector

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [10]:
# Changing shape and dtype
shape_vector = tf.constant([1,2,3],dtype=float,shape=[1,3])
shape_vector

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [11]:
# Changing dtype
another_matrix = tf.constant([[1.,2.],[3.,4.],[5.,6.],[7.,8.]],dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]], dtype=float16)>

In [12]:
# Create Tensor
tensor = tf.constant([[[1,2,],[3,4],
                       [5,6],[7,8],
                       [9,10],[11,12]]])
tensor

<tf.Tensor: shape=(1, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)>

In [13]:
# Check dimension
tensor.ndim

3

- Scalar has single constant so 0 dimension | a single number
- Vector has  row  so 1 dim | a number with direction
- Matrix has a row and a column so 2 dim | a 2-dimensional array of numbers
- Tensor has matrix then row then column so 3 dim | a n-dim array of numbers (n -> [0,infinity])
 

#### Creating tensors with `tf.Variable`

In [14]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Lets change value in changable tensor
# changable_tensor[0] = 8

In [16]:
# Let's try assign
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
# chaning unchangable tensor
# changable_tensor[0] = 7
# unchangable_tensor[0].assign(7)
# unchangable_tensor

In [18]:
# Creating Random Tensors
random_1 = tf.random.Generator.from_seed(42) # Set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [19]:
# Creting 2 random tensors from the same seed and checking their equality
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor

In [20]:
not_shuffled = tf.constant([[1,2],[3,4],[5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [21]:
shuffled_tensor = tf.random.shuffle(not_shuffled)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [22]:
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [23]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [24]:
# Other ways to create tensors
tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.zeros(shape=(10,5))

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [27]:
# We can change the shape and dtype
A1 = tf.constant(numpy_A,shape=(2,3,4),dtype=tf.float16)
A1

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float16)>

# Getting information from the tensors
- Shape -> The Length each dimension of a tensor | tensor.shape
- Rank -> The number of tensor dimension Scalar-0, Vector-1, Matrix-2, Tensor-n | tensor.ndim
- Axis or Dimension -> A particular dimension of a tensor | tensor[0], tensor[:1],.. etc
- Size -> Total Number of items in the tensor | tf.size(tensor)

In [28]:
A1.shape, A1.ndim, A1[1], tf.size(A1)

(TensorShape([2, 3, 4]),
 3,
 <tf.Tensor: shape=(3, 4), dtype=float16, numpy=
 array([[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]], dtype=float16)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [29]:
# Lets play a bit with Axis
A1[0], A1[1]

(<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
 array([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=float16)>,
 <tf.Tensor: shape=(3, 4), dtype=float16, numpy=
 array([[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]], dtype=float16)>)

In [30]:
# Lets Say I want to write my name R-18 A-1 M-13 A-1 N-14
A1[1][1][1], A1[0][0][0], A1[1][0][0], A1[0][0][0], A1[1][0][1]

(<tf.Tensor: shape=(), dtype=float16, numpy=18.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=13.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=14.0>)

In [31]:
# Create a rank 4 tensor  2,3,4,5
rank4 =  tf.zeros(shape=(2,3,4,5))
rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
print(tf.size(rank4))
print(tf.size(rank4).numpy())

tf.Tensor(120, shape=(), dtype=int32)
120


In [33]:
# Get the first two elements from each dimension
rank4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
# first element each dimension from each index except from the final one
rank4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank4[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [36]:
rank4[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [37]:
rank4[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [38]:
rank4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
# Create a rank 2 tensor
rank2 = tf.constant([[1,2],[3,4],[5,6]])
rank2
rank2.shape,rank2.ndim,tf.size(rank2), 

(TensorShape([3, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [40]:
# Get the last element of each of our rank2 tensor
rank2[:,-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [41]:
# Add extra dimension to our rank2 tensor
rank3 = rank2[..., tf.newaxis] # ... means every axis before this and add a new axis
rank3

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [42]:
# Alternative to tf.newaxis
tf.expand_dims(rank2,axis=-1)

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [43]:
tf.expand_dims(rank2,0) # Expand along 0 axis

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

### Manipulating the tensors (tensor operations)
**Basic Operations**
`+,-,*,/`

In [44]:
tens = tf.constant([[1,2],[3,4]])
tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [45]:
# Addition
# tens + 10, tens
tf.add(tens,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [46]:
# Notice the original tensor is unchanged the only way to change the tensor is by assigning it
# tens = tens+10
tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [47]:
# Multiplication
tens * 10
tf.multiply(tens,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [48]:
# Substraction
tens -10
tf.subtract(tens,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [49]:
# Division Just be 
tens / 10
tf.divide(tens,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [50]:
# This is called scalar operations
tf.math.add(tens,10), tf.math.subtract(tens,10), tf.math.multiply(tens,10), tf.math.divide(tens,10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-9, -8],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1, 0.2],
        [0.3, 0.4]])>)

# Matrix Multiplication
- It is one of the most common tensor operation in ML
- The inner dimensions must match
- Result matrix has the shape of outer dimensions


In [51]:
tf.linalg.matmul(tens,tens)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [52]:
tens * tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [53]:
# matrix multiplication with python operator `@`
tens @ tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [54]:
# Create a tensor with (3,2)
tens2 = tf.constant([[1,2],[3,4],[5,6]])
tens2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [55]:
tens2 @ tens

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22],
       [23, 34]], dtype=int32)>

In [56]:
# tens @ tens2

- So we can multiply (3,2) to (2,2) but not (2,2) to (3,2) because of last digit of the LHS should be same as the 1st digit of the RHS
- Hence in order to multiply it can we transform the shape of (3,2) to (2,3)


In [57]:
# Let's create two tensors of shape (3,2)
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [58]:
# X@Y

In [59]:
# tf.matmul(X,Y)

In [60]:
X.shape,Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [61]:
# Y = tf.reshape(Y,shape=(2,3))
# Y.shape

In [62]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
# what is we reshape X
tf.reshape(X,(2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [64]:
# Transpose exchanges rows with columns like (1,3) becomes (3,1)
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [65]:
# Transpose VS Reshape
X, tf.transpose(X), tf.reshape(X,(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [66]:
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [67]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

#### The Dot product
Matrix multiplication is also referred as dot product.
You can perform matrix multiplication using:
- tf.matmul()
- tf.tensordot()
- @


In [68]:
# Perfom dot product
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [69]:
# Matrix Multiplication with transposed Y
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [70]:
# Matrix multiplication with y reshaped
tf.tensordot(X, tf.reshape(Y,(2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [71]:
# Checking the values of Y and transposed Y and Reshaped Y
Y, tf.transpose(Y), tf.reshape(Y,(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [72]:
# Generally we transpose rather than reshaping when one of the axes doesnt match


In [73]:
# Changing datatype of a tensor
# Default is int32
B = tf.constant([1,2,3,4,5])
B.dtype

tf.int32

In [74]:
B = tf.constant([1.2,3.4])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 3.4], dtype=float32)>,
 tf.float32)

In [75]:
# Changing float32 to float16 (reduced precision)
D = tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.4], dtype=float16)>,
 tf.float16)

In [76]:
E = tf.cast(B,dtype=tf.int32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>,
 tf.int32)

#### Aggregating Tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values


In [77]:
C = tens - 3
C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -1],
       [ 0,  1]], dtype=int32)>

In [78]:
# Get Absolute values i.e. converting all negative values to positive values
tf.abs(C)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [0, 1]], dtype=int32)>

#### Let's go through the following forms of aggregation:
* Get the minimum of a tensor
* Get the maximum of a tensor
* Get the mean tensor
* Get the sum of a tensor

In [79]:
J = tf.constant(np.random.randint(0,100,50))
J

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([92,  7, 19, 88, 44, 14, 26, 68,  6, 35, 34,  0, 24, 59, 90, 18, 84,
       91, 69, 39, 60, 68, 45, 12, 93, 60, 44, 32, 39, 81, 40, 20, 46, 57,
       89, 36, 76, 79, 39, 96, 55, 27, 43, 69,  9,  3, 65, 53,  8,  1])>

In [80]:
# Getting the minimum
tf.reduce_min(J).numpy()

0

In [81]:
# Getting maximum
tf.reduce_max(J).numpy()

96

In [82]:
# Getting mean
tf.reduce_mean(J).numpy()

47

In [83]:
# Getting sum
tf.reduce_sum(J).numpy()

2352

In [84]:
# What does the axis parameter do
X.numpy(), tf.reduce_min(X,axis=0).numpy(), tf.reduce_min(X,axis=1).numpy()

(array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32),
 array([1, 2], dtype=int32),
 array([1, 3, 5], dtype=int32))

#### You can have different min max mean sum along different axis depending on the rank of the tensor </br>
#### 0 is for rows i.e. it checks through each row and 1 is for columns

In [85]:
# Find min max using math module
tf.math.reduce_max(J).numpy(), tf.math.reduce_mean(J), tf.math.reduce_min(J), tf.math.reduce_prod(J), tf.math.reduce_sum(J)

(96,
 <tf.Tensor: shape=(), dtype=int64, numpy=47>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2352>)

In [86]:
# Finding variance
tf.math.reduce_variance(tf.cast(J,tf.float32)).numpy()


810.03845

In [87]:
# Finding standard deviation

# J = tf.cast(J,dtype=tf.float64)
# J.dtype
tf.math.reduce_std(tf.cast(J,tf.float32)).numpy()


28.461174

# Or you can import tensorflow probablity

In [88]:
# import tensorflow_probablity as tfp
# tfp.stats.variance(J)

## Find positional Minimum and Maximum of a tensor

In [89]:
tf.math.argmin(J).numpy(), tf.math.argmax(J).numpy()

(11, 39)

In [90]:
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [91]:
tf.argmax(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

### Squeezing tensor (removing all single dimensions)


In [92]:
G = tf.constant(tf.random.uniform([50]),shape=([1,1,1,1,50]))
tf.random.set_seed(42)
# G = tf.random.uniform([50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [93]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [94]:
tf.squeeze(G).shape

TensorShape([50])

### One-hot encoding tensors


In [95]:
color = ['Red', "Green", "Blue", "Purple"]
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [96]:
# Specify custom values by specify on_value(1) and off_value(0)
tf.one_hot(some_list,depth=4,on_value="wii",off_value="ps5")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'wii', b'ps5', b'ps5', b'ps5'],
       [b'ps5', b'wii', b'ps5', b'ps5'],
       [b'ps5', b'ps5', b'wii', b'ps5'],
       [b'ps5', b'ps5', b'ps5', b'wii']], dtype=object)>

In [97]:
tf.one_hot(some_list,depth=4),tf.one_hot(some_list,depth=3),tf.one_hot(some_list,depth=2),tf.one_hot(some_list,depth=1)
# I think its beneficial if you take one less than it

(<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[1.],
        [0.],
        [0.],
        [0.]], dtype=float32)>)

In [98]:
### Squaring, log and Sqrt of tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [99]:
# Square H
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [105]:
# tf.math.log(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log] name: 

In [101]:
# Log
tf.math.log(tf.cast(H,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [104]:
# Sqrt H
tf.sqrt(tf.cast(H,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

### Tensors and Numpy


In [107]:
# Create tensor directly from a numpy array
K = tf.constant(np.arange(10))
K

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [110]:
# Converting tensor back to numpy array
K.numpy(),type(K.numpy())

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [111]:
# Or use np.array to directly convert it to numpy array
np.array(K), type(np.array(K))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [113]:
# The both use different default datatypes
numpy_K = tf.constant(np.arange(10))
tensor_K = tf.range(10)
numpy_K.dtype, tensor_K.dtype

(tf.int64, tf.int32)

In [115]:
# Find access to GPUs
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [116]:
!nvidia-smi

/bin/zsh: /home/stella/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/zsh)
Fri Aug 18 00:35:07 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 Ti     Off | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8               1W /  50W |   2856MiB /  4096MiB |      0%      Default |
|                                        