In [61]:
#1.Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
import tensorflow as tf
scalar = tf.constant(7)
vector = tf.constant([2,7])
matrix = tf.constant([[1,2],[3,4],[5,6],[7,8]])
tensor = tf.constant([[[1,2],[3,4],[5,6],[7,8]]])
scalar,vector,matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(1, 4, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]], dtype=int32)>)

In [4]:
#2. Find the shape, rank and size of the tensors you created in 1.
[scalar.shape, scalar.ndim, tf.size(scalar).numpy()],[vector.shape, vector.ndim, tf.size(vector).numpy()],[matrix.shape, matrix.ndim, tf.size(matrix).numpy()]


([TensorShape([]), 0, 1],
 [TensorShape([2]), 1, 2],
 [TensorShape([4, 2]), 2, 8])

In [22]:
#3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
tf.random.set_seed(42)
A = tf.random.uniform(shape=(5,300))
B = tf.random.uniform(shape=(5,300))
A,B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [26]:
#4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(A,tf.transpose(B))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.40498 , 77.15962 , 73.98367 , 80.900536],
       [75.146355, 68.804375, 74.24302 , 71.84183 , 75.602066],
       [79.7594  , 75.64456 , 77.79758 , 74.74873 , 80.559845],
       [75.08526 , 69.06407 , 74.307755, 72.27615 , 76.05668 ],
       [85.056885, 74.26627 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [33]:
#5.Multiply the two tensors you created in 3 using dot product.
tf.tensordot(A,tf.transpose(B),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.40498 , 77.15962 , 73.98367 , 80.900536],
       [75.146355, 68.804375, 74.24302 , 71.84183 , 75.602066],
       [79.7594  , 75.64456 , 77.79758 , 74.74873 , 80.559845],
       [75.08526 , 69.06407 , 74.307755, 72.27615 , 76.05668 ],
       [85.056885, 74.26627 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [35]:
#6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
C = tf.random.uniform(shape=(224,224,3))

In [40]:
#7.Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(C), tf.reduce_max(C)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.0967255e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999902>)

In [43]:
#8.Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
D = tf.random.uniform(shape=(1,224,224,3))
D.shape, tf.squeeze(D).shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [76]:
#9.Create a tensor with shape [10] using your own choice of values, then find the 
#index which has the maximum value.
import numpy as np
tf.random.set_seed(42)
E = tf.constant(np.random.randint(0,10,10), shape=(10),dtype=tf.int32)
tf.math.argmax(E).numpy(), E

(1,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 9, 4, 8, 6, 4, 2, 5, 6, 3], dtype=int32)>)

In [77]:
#10.One-hot encode the tensor you created in 9.
tf.one_hot(E,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Extra Curriculum
https://www.tensorflow.org/api_docs/python/tf/all_symbols


In [1]:
# TensorFlow quick start guide
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2023-08-30 18:48:10.672774: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-30 18:48:10.713893: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-30 18:48:10.715664: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-30 18:48:11.782627: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


TensorFlow version: 2.13.0


## Loading the data

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

## Building model

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-08-30 18:48:13.534174: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-30 18:48:13.534835: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.0395969 ,  0.0024148 , -0.5836802 ,  0.06646336,  0.04618925,
         0.28656355,  0.3871878 , -0.63854235,  0.24001308, -0.32795742]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.10361387, 0.09983204, 0.05555615, 0.10643534, 0.1042992 ,
        0.1326399 , 0.1466813 , 0.05259032, 0.12660696, 0.07174491]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.0201173

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2023-08-30 18:48:14.360512: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 5s 2ms/step - loss: 0.2924 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1414 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1054 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0870 - accuracy: 0.9742
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0751 - accuracy: 0.9764


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0707 - accuracy: 0.9774 - 411ms/epoch - 1ms/step


[0.0706866979598999, 0.977400004863739]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.4579362e-08, 9.9901065e-09, 5.3465105e-06, 1.4612408e-04,
        3.2800151e-10, 4.2103238e-07, 1.3023962e-12, 9.9984574e-01,
        3.0296542e-07, 1.7890915e-06],
       [4.0796671e-08, 3.6790614e-05, 9.9995065e-01, 1.2211213e-05,
        2.2235211e-14, 5.1895473e-08, 1.6539822e-07, 3.1248702e-12,
        1.1988752e-07, 6.6159358e-14],
       [1.9530837e-08, 9.9848193e-01, 1.6762217e-04, 1.9524348e-05,
        1.1628008e-05, 1.8210941e-06, 7.2070329e-06, 9.4485824e-04,
        3.6505275e-04, 3.0862131e-07],
       [9.9969232e-01, 3.5304506e-09, 2.0157415e-04, 3.7089123e-06,
        5.5816022e-06, 9.4360321e-06, 1.0825946e-05, 1.5447953e-05,
        7.2779665e-07, 6.0438455e-05],
       [2.0881585e-06, 1.0638517e-09, 3.8627273e-05, 1.3400988e-07,
        9.7162408e-01, 2.7379881e-06, 1.5425283e-05, 3.7157457e-04,
        5.1792149e-06, 2.7940026e-02]], dtype=float32)>